Quotient-filter based max cache filter

diff --git a/build_tools/build_detect_platform b/build_tools/build_detect_platform
--- a/build_tools/build_detect_platform
+++ b/build_tools/build_detect_platform
@@ -568,12 +568,14 @@ if test "$TRY_SSE_ETC"; then
   # source code." It's a qualifier on PORTABLE=1 that means "mostly portable."
   # It doesn't even really check that your current CPU is compatible.
   #
-  # SSE4.2 available since nehalem, ca. 2008-2010
+  # SSE4.2, POPCNT available since nehalem, ca. 2008-2010
   TRY_SSE42="-msse4.2"
+  TRY_POPCNT="-mpopcnt"
   # PCLMUL available since westmere, ca. 2010-2011
   TRY_PCLMUL="-mpclmul"
-  # AVX2 available since haswell, ca. 2013-2015
+  # AVX2, BMI2 available since haswell, ca. 2013-2015
   TRY_AVX2="-mavx2"
+  TRY_BMI2="-mbmi -mbmi2"
 fi
 
 $CXX $PLATFORM_CXXFLAGS $COMMON_FLAGS $TRY_SSE42 -x c++ - -o /dev/null 2>/dev/null <<EOF
@@ -588,6 +590,20 @@ if [ "$?" = 0 ]; then
   COMMON_FLAGS="$COMMON_FLAGS $TRY_SSE42 -DHAVE_SSE42"
 elif test "$USE_SSE"; then
   echo "warning: USE_SSE specified but compiler could not use SSE intrinsics, disabling" >&2
+fi
+
+$CXX $PLATFORM_CXXFLAGS $COMMON_FLAGS $TRY_POPCNT -x c++ - -o /dev/null 2>/dev/null <<EOF
+  #include <cstdint>
+  #include <x86intrin.h>
+  int main() {
+    volatile uint64_t x = _popcnt64(12345);
+    (void)x;
+  }
+EOF
+if [ "$?" = 0 ]; then
+  COMMON_FLAGS="$COMMON_FLAGS $TRY_POPCNT -DHAVE_POPCNT"
+elif test "$USE_SSE"; then
+  echo "warning: USE_SSE specified but compiler could not use POPCNT intrinsics, disabling" >&2
 fi
 
 $CXX $PLATFORM_CXXFLAGS $COMMON_FLAGS $TRY_PCLMUL -x c++ - -o /dev/null 2>/dev/null <<EOF
@@ -620,6 +636,22 @@ if [ "$?" = 0 ]; then
   COMMON_FLAGS="$COMMON_FLAGS $TRY_AVX2 -DHAVE_AVX2"
 elif test "$USE_SSE"; then
   echo "warning: USE_SSE specified but compiler could not use AVX2 intrinsics, disabling" >&2
+fi
+
+$CXX $PLATFORM_CXXFLAGS $COMMON_FLAGS $TRY_BMI2 -x c++ - -o /dev/null 2>/dev/null <<EOF
+  #include <cstdint>
+  #include <immintrin.h>
+  int main() {
+    volatile uint64_t x = _pdep_u64(12345, 1);
+    volatile uint64_t y = _tzcnt_u64(1234);
+    (void)x;
+    (void)y;
+  }
+EOF
+if [ "$?" = 0 ]; then
+  COMMON_FLAGS="$COMMON_FLAGS $TRY_BMI2 -DHAVE_BMI2"
+elif test "$USE_SSE"; then
+  echo "warning: USE_SSE specified but compiler could not use BMI2 intrinsics, disabling" >&2
 fi
 
 # iOS doesn't support thread-local storage, but this check would erroneously
